version: "3"
services:
  influxdb-park:
    container_name: influxdb-wj-test
    image: influxdb
    restart: always
    volumes:
      - ./data:/var/lib/influxdb/data
      - ./wal:/var/lib/influxdb/wal
      - ./meta:/var/lib/influxdb/meta
      - /etc/localtime:/etc/localtime
    ports:
      - 8083:8083
      - 8086:8086 
      - 8090:8090
        
